# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np  # Se importa la librería a usar: Numpy 

In [3]:
arreglo1=np.zeros(12)    # 1crear un arreglo de ceros de longitud 12
print(np.zeros(12))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
s= np.zeros(10,dtype=np.int64)  # 2crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición numero 5
s[5] = 10
s

array([ 0,  0,  0,  0,  0, 10,  0,  0,  0,  0], dtype=int64)

In [8]:
m= np.arange(10,50) # 3Crear un arreglo que tenga los números del 10 al 49 (con ayuda https://www.youtube.com/watch?v=h7LysAbfaM4)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
lista=[[0,1,2,],[3,4,5], [6,7,8]]                # 4Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
arr2d=np.array(lista)
arr2d                                         
    

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arreglo2 = np.arange(0, 9, 1).reshape((3, 3))  # con shape
arreglo2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arreglo3=np.random.randint(1,100, size=100)    # 5Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza (con ayuda https://www.youtube.com/watch?v=VBQhErvtHRc)
media=np.mean(arreglo3)
print (media)
var=np.var(arreglo3)
print (var)
print (arreglo3)

52.63
666.1531
[35 41 54 99 78 78 55 87 30 50 75 56 71 43 36 50  2 54 86  1 52 82 54 18
 38 56 28 58 38 14 34 28 84 28 48 43 85 63 28 50 90 24 61 98 23 25 49 40
 14 40 69 51 87 68 22 37 55 98 48 77 72 97 27 69 42 58 88 49 29 83 32 15
 17 51 41 93 84 72 83 55 77 54 35 56 84 27 23 40  2 27 98  5 64 71 63 92
 64 28 12 98]


In [21]:
media1=np.sum(arreglo3)/(100)          # 6Calcular la media de un arreglo usando np.sum     


50.99

In [26]:
arreglo4= np.random.randint(0,100,10)
var1 = (np.sum((arreglo4 - np.mean(arreglo4)) ** 2)) / arreglo4.size      # 7Calcular la varianza de un arreglo usando np.sum y np.mean
print(f'La varianza es: {var1} (calculada con np.sum() y np.mean())')     


La varianza es: 556.4100000000001 (calculada con np.sum() y np.mean())


In [32]:
  np.random.rand(23)                                          # 8Crear un array de números aleatorios usando np.random.randn.

array([0.61442601, 0.57098575, 0.77673831, 0.96380462, 0.56757579,
       0.38962544, 0.69363513, 0.86199802, 0.89407263, 0.24797917,
       0.75564904, 0.21788765, 0.99560787, 0.08936478, 0.87986134,
       0.12446429, 0.09988536, 0.20456167, 0.74376289, 0.56916002,
       0.20486249, 0.88050234, 0.72224188])